- name: "4.1.1.1 | Ensure auditd is installed (Scored)"
  yum:
    name:
      - "audit"
      - "audit-libs"
    state: present
  when:
    - rule_4_1_1_1
  tags:
    - level1
    - level2
    - rule_4.1.1.1
    - section_4

- name: "4.1.1.2 | Ensure auditd service is enabled (Scored)"
  systemd:
    name: auditd
    state: started
    enabled: yes
  when:
    - rule_4_1_1_2
  tags:
    - level2
    - auditd
    - rule_4.1.1.2
    - section_4

- name: "4.1.1.3 | Ensure auditing for processes that start prior to auditd is enabled (Scored)"
  replace:
    dest: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!audit=1)(?:")'
    replace: '\1"\2 audit=1"'
    follow: yes
  ignore_errors: yes
  notify: generate new grub config
  when:
    - rule_4_1_1_3
  tags:
    - level2
    - auditd
    - rule_4.1.1.3
    - section_4

- name: "4.1.1.4 | Ensure audit_backlog_limit is sufficient (Scored)"
  block:
    - name: "4.1.1.4 | Ensure audit_backlog_limit is sufficient (Scored) | Check config"
      command: grep -E "GRUB_CMDLINE_LINUX=.*audit_backlog_limit={{ audit_backlog_limit }}.*" /etc/default/grub
      register: grep_audit_backlog_grub
      failed_when: false
      changed_when: false

    - name: "4.1.1.4 | Ensure audit_backlog_limit is sufficient (Scored) | Update config"
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"$'
        line: 'GRUB_CMDLINE_LINUX="\1 audit_backlog_limit={{ audit_backlog_limit }}"'
        state: present
        owner: root
        group: root
        mode: 0644
        backrefs: true
      notify: generate new grub config
      when:
        - grep_audit_backlog_grub.rc == 1
  when:
    - rule_4_1_1_4
  tags:
    - level2
    - auditd
    - rule_4.1.1.4
    - section_4

- name: "4.1.2.1 | Ensure audit log storage size is configured (Scored)"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file( |=)"
    line: "max_log_file = {{ auditd['max_log_file'] }}"
    state: present
  when:
    - rule_4_1_2_1
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.2.1
    - section_4

- name: "4.1.2.2 | Ensure audit logs are not automatically deleted (Scored)"
  lineinfile:
    dest: /etc/audit/auditd.conf
    regexp: "^max_log_file_action"
    line: "max_log_file_action = {{ auditd['max_log_file_action'] }}"
    state: present
  when:
    - rule_4_1_2_2
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.2.2
    - section_4

- name: "4.1.2.3 | Ensure system is disabled when audit logs are full (Scored)"
  block:
    - name: "4.1.2.3 | Ensure system is disabled when audit logs are full (Scored)"
      lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^admin_space_left_action"
        line: "admin_space_left_action = {{ auditd['admin_space_left_action'] }}"
        state: present
      notify: restart auditd

    - name: "4.1.2.3 | Ensure email on non-admin audit space alert (Scored)"
      lineinfile:
        dest: /etc/audit/auditd.conf
        regexp: "^space_left_action"
        line: "space_left_action = email"
        state: present
      notify: restart auditd
  when:
    - rule_4_1_2_3
  tags:
    - level2
    - auditd
    - rule_4.1.2.3
    - section_4

- name: "4.1.3 | Ensure changes to system administration scope (sudoers) is collected (Scored)"
  template:
    src: audit/rule_4_1_3.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_3.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_3
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.3
    - section_4

- name: "4.1.4 | Ensure login and logout events are collected (Scored)"
  template:
    src: audit/rule_4_1_4.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_4.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_4
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.8
    - section_4

- name: "4.1.5 | Ensure session initiation information is collected (Scored)"
  template:
    src: audit/rule_4_1_5.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_5.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_5
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.5
    - section_4

- name: "4.1.6 | Ensure events that modify date and time information are collected (Scored)"
  template:
    src: audit/rule_4_1_6.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_6.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_6
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.6
    - section_4

- name: "4.1.7 | Ensure events that modify the system's Mandatory Access Controls are collected (Scored)"
  template:
    src: audit/rule_4_1_7.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_7.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_7
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.7
    - section_4

- name: "4.1.8 | Ensure events that modify the system's network environment are collected (Scored)"
  template:
    src: audit/rule_4_1_8.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_8.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_8
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.8
    - section_4

- name: "4.1.9 | Ensure discretionary access control permission modification events are collected (Scored)"
  template:
    src: audit/rule_4_1_9.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_9.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_9
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.9
    - section_4

- name: "4.1.10 | Ensure unsuccessful unauthorized file access attempts are collected (Scored)"
  template:
    src: audit/rule_4_1_10.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_10.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_10
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.10
    - section_4

- name: "4.1.11 | Ensure events that modify user/group information are collected (Scored)"
  template:
    src: audit/rule_4_1_11.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_11.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_11
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.11
    - section_4

- name: "4.1.12 | Ensure successful file system mounts are collected (Scored)"
  template:
    src: audit/rule_4_1_12.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_12.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_12
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.12
    - section_4

- name: "4.1.13 | Ensure use of privileged commands is collected (Scored)"
  shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
  register: priv_procs
  changed_when: no
  check_mode: no
  when:
    - rule_4_1_13
  tags:
    - level2
    - auditd
    - rule_4.1.13
    - section_4

- name: "4.1.13 | Ensure use of privileged commands is collected (Scored)"
  template:
    src: audit/rule_4_1_13.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_13.rules
    owner: root
    group: root
    mode: 0600
  notify: restart auditd
  when:
    - rule_4_1_13
  tags:
    - level2
    - auditd
    - rule_4.1.13
    - section_4

- name: "4.1.14 | Ensure file deletion events by users are collected (Scored)"
  template:
    src: audit/rule_4_1_14.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_14.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_14
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.14
    - section_4

- name: "4.1.15 | Ensure kernel module loading and unloading is collected (Scored)"
  template:
    src: audit/rule_4_1_15.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_15.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_15
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.15
    - section_4

- name: "4.1.16 | Ensure system administrator actions (sudolog) are collected (Scored)"
  template:
    src: audit/rule_4_1_16.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_16.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_16
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.16
    - section_4

- name: "4.1.17 | Ensure the audit configuration is immutable (Scored)"
  template:
    src: audit/rule_4_1_17.rules.j2
    dest: /etc/audit/rules.d/rule_4_1_17.rules
    owner: root
    group: root
    mode: 0600
  when:
    - rule_4_1_17
  notify: restart auditd
  tags:
    - level2
    - auditd
    - rule_4.1.17
    - section_4

- name: "4.2.1.1 | Ensure rsyslog is installed (Scored)"
  dnf:
    name: rsyslog
    state: present
  when:
    - rule_4_2_1_1
  tags:
    - level1
    - level2
    - rule_4.2.1.1
    - section_4

- name: "4.2.1.2 | Ensure rsyslog Service is enabled (Scored)"
  systemd:
    name: rsyslog
    state: started
    enabled: yes
  when:
    - rule_4_2_1_2
  tags:
    - level1
    - level2
    - rule_4.2.1.2
    - section_4
    - notimplemented

- name: "4.2.1.3 | Ensure rsyslog default file permissions configured (Scored)"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: "$FileCreateMode 0640"
  when:
    - rule_4_2_1_3
  tags:
    - level1
    - level2
    - rule_4.2.1.3
    - section_4

- name: "4.2.1.4 | Ensure logging is configured (Not Scored)"
  command: /bin/true
  changed_when: no
  when:
    - rule_4_2_1_4
  tags:
    - level1
    - level2
    - rule_4.2.1.4
    - section_4

- name: "4.2.1.5 | Ensure rsyslog is configured to send logs to a remote log host (Scored)"
  lineinfile:
    dest: /etc/rsyslog.conf
    insertbefore: "^$FileCreateMode 0640"
    line: "*.* @{{ rsyslog_dest  }}"
  when:
    - rule_4_2_1_5
  tags:
    - level1
    - level2
    - rule_4.2.1.5
    - section_4

- name: "4.2.1.6 | Ensure remote rsyslog messages are only accepted on designated log hosts (Not Scored)"
  command: /bin/true
  changed_when: no
  when:
    - rule_4_2_1_6
  tags:
    - level1
    - level2
    - rule_4.2.1.6
    - section_4
    - notimplemented

- name: "4.2.2.1 | Ensure journald is configured to send logs to rsyslog (Scored)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^ForwardToSyslog"
    line: "ForwardToSyslog=yes"
    state: present
  when:
    - rule_4_2_2_1
  tags:
    - level1
    - rule_4.2.2.1
    - section_4

- name: "4.2.2.2 | Ensure journald is configured to compress large log files (Scored)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^Compress"
    line: "Compress=yes"
    state: present
  when:
    - rule_4_2_2_2
  tags:
    - level1
    - rule_4.2.2.2
    - section_4

- name: "4.2.2.3 | Ensure journald is configured to write logfiles to persistent disk (Scored)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^Storage"
    line: "Storage=persistent"
    state: present
  when:
    - rule_4_2_2_3
  tags:
    - level1
    - rule_4.2.2.3
    - section_4

- name: "4.2.3 | Ensure permissions on all logfiles are configured (Scored)"
  block:
    - name: "4.2.3 |  Ensure permissions on all logfiles are configured (Scored) | Get files"
      command: find /var/log -type f -perm /037
      register: logfile_wrong_permissions
      failed_when: false
      changed_when: false

    - name: "4.2.3 | Ensure permissions on all logfiles are configured (Scored) | Get directories"
      command: find /var/log -type d -perm /026
      register: logdir_wrong_permissions
      failed_when: false
      changed_when: false

    - name: "4.2.3 | Ensure permissions on all logfiles are configured (Scored) | Set files permissions"
      file:
        dest: "{{ item }}"
        mode: 0640
      with_items: "{{ logfile_wrong_permissions.stdout_lines }}"
      when: logfile_wrong_permissions.stdout_lines | length > 0

    - name: "4.2.3 | Ensure permissions on all logfiles are configured (Scored) | Set directories permissions"
      file:
        dest: "{{ item }}"
        state: directory
        mode: 0750
      with_items: "{{ logdir_wrong_permissions.stdout_lines }}"
      when: logdir_wrong_permissions.stdout_lines | length > 0
  when:
    - rule_4_2_3
  tags:
    - level1
    - level2
    - rule_4.2.3
    - section_4

- name: "4.3 | Ensure logrotate is configured (Not Scored)"
  block:
    - name: "4.3 | Ensure logrotate is configured (Not Scored)"
      find:
        paths: /etc/logrotate.d/
      register: log_rotates

    - name: "4.3 | Ensure logrotate is configured (Not Scored)"
      replace:
        path: "{{ item.path }}"
        regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
        replace: "\\1{{ logrotate }}"
      with_items:
        - "{{ log_rotates.files }}"
        - { path: "/etc/logrotate.conf" }
  tags:
    - level1
    - level2
    - rule_4.3
    - section_4
